### ISSUE TITLE
New `M-;` doesn't suit this user

### ISSUE THREAD

**Issue by monnier** [ocaml/tuareg#149]
I just discovered the new behavior of `M-;` introduced by commit ed5cc2a5d6b1451314eb2d55fa5ab2db0fa6803a and I clearly don't like it.

Historically, `M-;` did not do any region-oriented commands and only added a comment at the end of the current line (or jumped to it if there was one already), and I still expect this functionality from `M-;` whereas it seems like the new `M-;` does not offer this functionality at all.

Of course, I know how to fix this for myself.  And of course, I prefer the default `comment-dwim` to this new function since I'm the author of `comment-dwim` (i.e. it clearly reflects my own preferences).

So take this issue with a grain of salt since I'm obviously biased, but despite this, I think there's a real problem: the new behavior of `M-;` in Tuareg has nothing to do with OCaml (none of its new behavior can be justified by some specific feature of the OCaml syntax, for example), so I think it does not belong in Tuareg.  It should be in another package (and apply globally rather than only for `tuareg-mode`).

Similarly, I don't see which part of `tuareg-comment-or-uncomment-region` is specific to OCaml.  Maybe this should be turned into a patch for Emacs's `comment-or-uncomment-region`.

**Comment by Chris00** [comment]
What _default_ key combination would be suitable?  (This feature is an attempt to "quench" the request for single line comments in OCaml.)

**Comment by erikmd** [comment]
Hi, IINM we can get the standard behavior (comment-dwim) by doing `C-e M-;` instead of `M-;`.
So it's one more keystroke w.r.t before (and not that easy to type because it combines Ctrl and Meta).
BTW I just did some `C-h b` and grep "comment" inside the help buffer, and it appears there is a function from `newcomment.el` very close to `tuareg-comment-or-uncomment-region` with a simpler binding:
`comment-line is on C-x C-;`
Kind regards

**Comment by monnier** [comment]
@Chris00, there is no "quench for single-line comments in OCaml" : there's instead a "quench for single-line comments in Emacs".   So better redirect those requests to Emacs's maintainers, otherwise every major mode will invent its own solution.

**Comment by erikmd** [comment]
Hi @Chris00 @monnier 
Do you confirm that the new behaviour of `tuareg-comment-dwim` from ed5cc2a5d6b1451314eb2d55fa5ab2db0fa6803a is the same as that of function `comment-line`?

IIUC in this case, `tuareg-comment-dwim` could be removed to put forth the original `comment-dwim` on `M-;` and `comment-line` on `C-x C-;`, and otherwise if there's OCaml-specific code regarding single line commenting, this code could be associated to `C-x C-;` rather than to `M-;`. So in both cases `M-;` would be restored to the vanilla behavior of `comment-dwim`.
Do you agree with this or am I missing something?

**Comment by mookid** [comment]
Alternative: just advertise the existence of the command in the documentation without binding it to any key sequence.
