### ISSUE TITLE
Un-git `tuareg-site-file.el`

### ISSUE THREAD

**Issue by mattiase** [ocaml/tuareg#272]
As far as I can tell, the file will be generated in the rules where it is needed. I'm a bit fed up with seeing it as modified each time after rebuilding the `elc` files.

**Comment by Chris00** [comment]
I guess there was a reason in including it.  @monnier?

**Comment by monnier** [comment]
Christophe Troestler [2021-09-03 12:33:00] wrote:
> I guess there was a reason in including it.  @monnier?

Hmm... indeed it seems I'm to blame.  Can I invoke an insanity defense?
Or should I plead the fifth?

More seriously, I think I included it in commit 14ccd9d432d13cea6b
because that "just" renamed `dot-emacs.el` to `tuareg-site-lisp.el` and
I didn't want to rock the boat any further.

I'd be very happy to remove this file, especially since it is not used
when Tuareg is distributed/installed via ELPA.

**Comment by Chris00** [comment]
Thanks — I was not sure it was not used by (M)ELPA.

**Comment by mattiase** [comment]
Thank you! What about adding the file to `.gitignore` as well?
