### ISSUE TITLE
Support exception branches in match

### ISSUE THREAD

**Issue by roysc** [ocaml/tuareg#42]
In OCaml 4.02, `match` expressions have been [extended](https://ocaml.org/releases/4.02.html) to allow `exception` branches. This isn't recognized yet, and using the syntax throws off font-lock and indentation.

```ocaml
let n = match List.find ((=) 3) [1;2] with
  | x -> x
  | exception Not_found -> 0
              in n               (* Should be at leftmost indentation *)
```

**Comment by moosotc** [comment]
Placing braces around exception specification alleviates the problem somewhat, still a proper solution would be nice.

**Comment by monnier** [comment]
The patch below should add support for that new syntax.

diff --git a/tuareg.el b/tuareg.el
index 9bd6d95..ed20b64 100644
--- a/tuareg.el
+++ b/tuareg.el
@@ -1272,7 +1272,10 @@ by |, insert one |."
               (iddef (id "f=" exp1))
               (branches (branches "|" branches) (branch))
               (branch (patterns "->" exp1))
-              (patterns (pattern) (pattern "when" exp1))
+              (patterns (pattern) (pattern "when" exp1)
+                        ;; Since OCaml 4.02, `match' expressions allow
+                        ;; `exception' branches.
+                        ("exception-case" pattern))
               (pattern (id) (pattern "as" id) (pattern "," pattern))
               (class-body (class-body "inherit" class-body)
                           (class-body "method" class-body)
@@ -1452,7 +1455,8 @@ of the token."
         (goto-char (match-end 0))
         (match-string 0)))
      ((or (member tok '("let" "=" "->"
-                        "module" "class" "open" "type" "with" "and"))
+                        "module" "class" "open" "type" "with" "and"
+                        "exception"))
           ;; http://caml.inria.fr/pub/docs/manual-ocaml/expr.html lists
           ;; the tokens whose precedence is based on their prefix.
           (memq (aref tok 0) '(?* ?/ ?% ?+ ?- ?@ ?^ ?= ?< ?> ?| ?& ?$)))
@@ -1610,6 +1614,9 @@ Return values can be
             "label:"
           (goto-char pos)
           tok)))
+     ((equal tok "exception")
+      (if (save-excursion (equal (tuareg-smie--backward-token) "|"))
+          "exception-case" tok))
      ((string-match "\\`[[:alpha:]_].*\\.\\'"  tok)
       (forward-char (1- (length tok))) ".")
      (t tok))))

**Comment by Chris00** [comment]
The version at the time of this comment is
```ocaml
let f =
  let n =
    match List.find ((=) 3) [1;2] with
    | x -> x
    | exception Not_found -> 0
  in n
```
so I think we can consider this fixed.
