### ISSUE TITLE
circular dependencies

### ISSUE THREAD

**Issue by andreas-roehler** [ocaml/tuareg#52]
At the end of tuareg.el:

;; Pre-SMIE indentation functions.
;; Load it after providing `tuareg' to avoid circular dependencies.
(require 'tuareg_indent)

However in tuareg_indent.el resides:

(require 'tuareg)

So the circular is already there.

Will fix this alongside with in-string/comment re-write

**Comment by andreas-roehler** [comment]
IMO the way to go is keeping tuareg.el as a kind of master-file, while reading needed internals from others at start.

**Comment by Chris00** [comment]
Doesn't [this](https://github.com/ocaml/tuareg/commit/b15fe7f4517aa4e28012f16c85d73aec33d6507d#diff-5eb18a62fdf44d1d0a3a3c3a8f10141cR2961) solves this issue?

**Comment by monnier** [comment]
I must say I don't what is this "issue" about.  There are indeed circular "requires" between the two files, but since the (require 'tuareg_indent) happens after (provide 'tuareg) the circularity should never result in infinite recursion.  In the worst case (i.e. when loading tuareg_indent) we'll end up loading tuareg and then loading tuareg_indent again (and the recursion stops there).  It's kind of ugly, but to solve this "right" we'd have to split some code into a third file which is the required by both files.  To the extent that tuareg_indent should hopefully end up deprecated and then dropped (in some moderately distant future), I don't think it's worth the trouble.
